services:
  mariadb:
    image: mariadb:11.8
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD-SHELL", "mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'SELECT 1'"]
      interval: 1s
      timeout: 2s
      retries: 5

  deno:
    build: .
    working_dir: /app
    volumes:
      - ./apps/api/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
